name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PEM_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run:
        ssh -i ~/.ssh/ec2_key.pem $EC2_USER@$EC2_HOST
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.2'
    
#     - name: Install Composer dependencies
#       run: composer install --prefer-dist --no-progress
    
#     - name: Run tests
#       run: vendor/bin/phpunit
